### PR TITLE
fix: Reset lens state when calling Reset

### LINKED ISSUE #46: Reset module state (not including params) on enumerable.Reset
State can be leaked between contexts as modules are reused and reset needs to clear non-parameter state.

This currently affects Defra-Lens, there is a todo code-comment in the code there  linked to this issue which should be removed once this ticket has been done.

-----

I see three possible ways of resetting:
1. Zero the memory from the host.  This is *very* unsafe as any state set on runtime init will be wiped, yet the language that the module is written in will not flag this. It might also not work, as it might remove the lens functions (untested).
2. Re-initialise the module.  This is very slow (wazero taking 56ms on my machine for a tiny module).  This is the most certain option, and will be safe.
3. Allow lenses to optionally provide a `reset` function, and allow them to control which state gets reset.  This is more powerful, and allows some state to be preserved if desired.  It does however, in the current Defra context allow for data leakage across ACP boundaries - the lens can chose (or forget) to wipe sensitive state from one user, and allow it to be used in the context of another use that might not have read access to that state.

At the moment, I think both option 2 and 3 are needed.  The ACP problem in option 3 is IMO an application code problem (where Defra is the application), although the Lens store/node should allow the key/caching of data by an externally provided discriminator, so that different Defra (or other) users/permissions can be cached separately (especially if the Lens author is untrusted).  This keying could perhaps be driven by a prop on ctx, but I don't think I like that (transparency problems).

Option 2 should probably be coupled with the dynamic resizing of the lens pool, so that the application can chose to grow/shrink instances according to user demand (no point keeping 5 instances in memory for a user/permission-set who uses Defra once a month).

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #46

## Description

Resets lens state when calling Reset to how it was after configuration but before items were passed through it.

### CODE REVIEW

File: tests/action/transform.go [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+			require.NoError(a.s.T, err)
+
+			require.Equal(a.s.T, expectedValue, value)
+		}
+
+		expectedHasNext, err := a.Expected.Next()
+		require.NoError(a.s.T, err)
+		require.False(a.s.T, expectedHasNext)
+
+		a.Expected.Reset()
```
Comment (islamaliev) [inline tests/action/transform.go]: todo: I might be missing something here, but the action is call `Transform` and calls for some reason `Reset` which I'm sure if test writer or reader would/should necessarily expect.

Please document it somewhere.

File: tests/action/transform_reset.go [hunk 2]
```diff
@@ -0,0 +1,20 @@
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at https://mozilla.org/MPL/2.0/.
+
+package action
+
+type TransformReset struct {
```
Comment (islamaliev) [inline tests/action/transform_reset.go]: suggestion: documentation would be nice here

**Review by islamaliev — APPROVED** [review]
Looks good overall. I left some minor suggestions/requets

File: tests/integration/node/add_transform_reset_test.go [hunk 3]
```diff
@@ -0,0 +1,189 @@
...
+							"Id":   float64(1),
+						},
+						{
+							"Name": "Addo",
+							"Id":   float64(2),
+						},
+					},
+				),
+			},
+			&action.TransformReset{
```
Comment (fredcarle) [inline tests/integration/node/add_transform_reset_test.go]: thought: Would be nice to show what happens if reset isn't called.

Comment (fredcarle) [reply tests/integration/node/add_transform_reset_test.go]: Yes a new test committed to main. It would be good documentation that shows what could happen if reset is not used.
