### PR TITLE
fix: Add Lens to repository on sync

### LINKED ISSUE #142: SyncLens never adds synced lenses to repository
Forcing users to call `Reload` if they ever want to use the Lens (it is visible in List).

### PR DESCRIPTION
**Pull request by AndrewSisley**
## Relevant issue(s)

Resolves #142

## Description

Add Lens to repository on `SyncLens`.

Otherwise users are forced to call `store.Reload()` in order to actually use their synced lens.

The code is a bit messy, but the public changes are small (a new store constructor, and a private func made public).

Tested via Defra.

### CODE REVIEW

File: host-go/store/store.go [hunk 1]
```diff
@@ -89,6 +89,25 @@ func New(
 	}
 }
 
+// NewR creates a new `TxnStore` using the given parameters.
+//
+// The blockstore namespace may safely be shared by other components if desired.
+func NewR(
```
Comment (fredcarle) [inline host-go/store/store.go]: suggestion: `NewWithRepository`. It's longer but less cryptic.

**Review by fredcarle — APPROVED** [review]
Just one suggestion before merge.
